[package]
name = "lunatic-ex"
version = "0.1.0"
edition = "2021"

[dependencies]
lunatic = { version = "0.14.1", features = ["msgpack_serializer"] }
serde = { version = "1.0.204", features = ["derive"] }

[build]
target = "wasm32-wasi"

[target.wasm32-wasi]
runner = "lunatic run"
